data("cdc13-1vsURA3_IHM")
burn=1
iters=1
thin=1
aa<-QFA.NoORFA
bb<-QFA.NoORFB
if(!(length(aa)==length(bb))){stop()}
L=length(aa)
NCOL=
L+
1+
1+
L+
1+
1+
1+
L+
L+
1+
1+
1
tmp <- .C("main_IHM", as.integer(burn),as.integer(iters),as.integer(thin),OUT=as.double(1:(NCOL*iters)),HEADER=as.character(rep("NULLNULL",NCOL)),
QFAIA=QFA.IA,QFAy=QFA.yA,QFANoORFA=QFA.NoORFA,
QFAIB=QFA.IB,QFAy=QFA.yB,QFANoORFB=QFA.NoORFB,
PRIORS=PRIORS
)
mat=matrix((tmp$OUT),nrow=iters,byrow=T)
mat=data.frame(mat)
names(mat)=tmp$HEADER
mat

